name: Deploy

on:
  push:
    branches: ['main']
    paths:
      - 'project.inlang/**'
      - 'scripts/**'
      - 'src/**'
      - 'static/**'
      - '*.{js,ts}'
      - 'package.json'
      - 'pnpm-*.yaml'
      - '.github/workflows/deploy.yml'

  pull_request:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: 'deploy'
  cancel-in-progress: false

env:
  default_node_version: ''
  default_pnpm_version: '10'
  artifact_name: 'github-pages'
  default_destination: 'build'
  temp_dir: '.temp'

jobs:
  build:
    name: Build
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v6
        with:
          version: ${{ env.default_pnpm_version }}

        name: Install pnpm
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ env.default_node_version }}
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: build
        run: pnpm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ${{ env.default_destination }}

  deploy_ghp:
    if: ${{ github.event_name != 'pull_request' }}
    name: Deploy to Github Pages
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5

  deploy_surge:
    if: ${{ github.event_name != 'pull_request' }}
    name: Deploy to Surge
    needs: build
    runs-on: ubuntu-slim
    environment:
      name: 'surge'
      url: ${{ steps.get_url.outputs.url }}
    permissions:
      contents: read
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: ${{ env.artifact_name }}
          path: ${{ env.temp_dir }}
      - run: |
          mkdir -p ${{ env.default_destination }} || echo "1"
          tar -xvf ${{ env.temp_dir }}/artifact.tar -C ${{ env.default_destination }}
      - run: npm install -g surge
      - run: surge ${{ env.default_destination }} --token ${{ secrets.SURGE_TOKEN }}
      - run: echo -n "url=$(cat ${{ env.default_destination }}/CNAME)" >> "$GITHUB_OUTPUT"
        id: get_url
